Change mail command installation based on distro ID
Added -u and --update command to update script

diff --git a/maxibuild b/maxibuild
--- a/maxibuild
+++ b/maxibuild
@@ -2,12 +2,115 @@
 #"=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~="
 # ==================================================
 _APP_SPECIFIC_NAME="Maxibuild"
-_APP_VERSION="0.1.7"
+_APP_VERSION="0.1.8"
 _APP_STATUS="alpha"
 _APP_INFO="${_APP_SPECIFIC_NAME} is a bash script to manage packages."
 _APP_VERSION_STATUS="${_APP_VERSION}-${_APP_STATUS}"
 _AUTHOR="Author: Arafat Ali | Email: arafat@sofibox.com | (C) 2019-2022"
 # ====================================================
+
+# This script is used to update script from a remote repository based on a given path
+# Usage: update_script [script_path]
+# Example: update_script /opt/maxigpg_public/
+script_update() {
+  local script_name script_path caller script_install_path current_configs new_configs
+
+  script_name="$(basename "${0}")"
+  script_path="$(dirname "$(readlink -f "$0")")"
+  caller="${script_name}->${FUNCNAME[0]}"
+  script_install_path="${1}"
+
+  echo "[${caller}]: Updating $(basename -- "$0") to latest version ..."
+  # CD to ${script_path} and if does not exist exit with error
+  cd "${script_path}" || {
+    echo "[${caller}]: ERROR, could not change directory to ${script_path}"
+    exit 1
+  }
+  echo ""
+  echo "START git update information:"
+  git fetch --all
+  get_status_message "$?"
+  git reset --hard origin/main
+  get_status_message "$?"
+  echo "END git update information:"
+  echo ""
+  navigate_to "PREVIOUS"
+  echo ""
+
+  echo "[${caller}]: Updating ${script_name} configuration file ..."
+
+  # This will add a new config variable into the config file if it does not exist
+  # It will not disturb variable that already has value. So you do not need to reconfigure the script
+  # If config contain invalid value like having no equal sign, it will also replace them with a new variable from sample config
+
+  current_configs=$(grep -E '^[A-Za-z0-9_].+=.+$' "${script_install_path}/${script_name}.conf" | awk -F "=" '{print $1}')
+  new_configs=$(grep -E '^[A-Za-z0-9_].+=.+$' "${script_install_path}/${script_name}.conf.sample" | awk -F "=" '{print $1}')
+
+  for new_config in ${new_configs}; do
+    if [[ ${current_configs} =~ ${new_config} ]]; then
+      :
+    else
+      echo "Adding new config: ${new_config} into ${script_install_path}/${script_name}.conf"
+      echo "${new_config}=\"\"" >>"${script_install_path}/${script_name}.conf"
+      get_status_message "$?"
+    fi
+  done
+
+  # Remove blank lines, comments and sort config file
+  grep -E '^[A-Za-z0-9_].+=.+$' "${script_install_path}/${script_name}.conf" | sort >"${script_install_path}/${script_name}.conf_tmp"
+  mv "${script_install_path}/${script_name}.conf_tmp" "${script_install_path}/${script_name}.conf"
+  get_status_message "$?"
+
+  echo "[${caller}]: Running ${script_name} -V ..."
+  chmod +x "${script_install_path}/${script_name}"
+  ${script_name} -V
+  get_status_message "$?"
+
+}
+
+# This function is used to check for script update. It will also prompt user to update the script if there is a new version available.
+# Usage: check_update
+# Example: check_update
+check_update() {
+  local script_name script_path caller temp_file script_install_path
+  script_name="$(basename "${0}")"
+  script_path="$(dirname "$(readlink -f "$0")")"
+  caller="${script_name}->${FUNCNAME[0]}"
+  script_install_path="/usr/local/maxicode/maxibuild"
+  echo "[${caller}]: Checking ${script_name} for update..."
+  temp_file="${TEMP_PATH}/${script_name}"
+  # The github raw hosting will not be updated immediately after I push the update to github. Need to wait about 5 minutes
+  if ! command -v curl &>/dev/null; then
+    [[ "$(get_distro id)" == +(debian|ubuntu|centos|almalinux|rhel) ]] && apt-get install -y curl
+  fi
+  curl -H 'Cache-Control: no-cache' -so "${temp_file}" "https://raw.githubusercontent.com/sofibox/${script_name}_public/main/${script_name}"
+  get_status_message "$?"
+  available_version="$(awk -F'=' '/^_APP_VERSION=/{ print $2 }' "${temp_file}" | sed 's/\"//g')"
+  this_version="${_APP_VERSION}"
+  echo ""
+  echo "Installed version is: v${this_version}"
+  echo "Online version is: v${available_version}"
+  echo ""
+  if [[ "ok" == "$(echo | awk "(${available_version} > ${this_version}) { print \"ok\"; }")" ]]; then
+    echo "[${caller}]: A new version of ${script_name} is available."
+
+    read -r -p "[${caller}->input]: Do you want to update ${script_name} to version ${available_version}? [default:Y] [Y/n]: " response
+
+    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
+      script_update "${script_install_path}"
+    else
+      echo "[${caller}->cancel]: Operation aborted!"
+      exit 0
+    fi
+
+  elif [[ "ok" == "$(echo | awk "(${available_version} == ${this_version}) { print \"ok\"; }")" ]]; then
+    echo "[${caller}]: You are using the latest version of ${script_name}."
+  else
+    echo "[${caller}]: You are using a newer version of ${script_name} than the latest available."
+  fi
+
+  rm -f "${temp_file}"
+}
 
 # This function is used to check if given package is installed and install the package if it is not installed
 # It will not do anything if the required package exist
@@ -116,7 +219,8 @@ maxibuild() {
 
       # Package installation condition here
       if [ "${required_cmd}" == "mail" ]; then
-        [[ "$(get_distro id)" == +(debian|ubuntu) ]] && apt-get -y install mailutils
+        [[ "$(get_distro id)" == +(debian|ubuntu) ]] && apt-get -y install bsd-mailx
+        [[ "$(get_distro id)" == +(centos|almalinux|rockylinux) ]] && apt-get -y install bsd-mailx
         retval=$?
       elif [ "${required_cmd}" == "ipcalc" ]; then
         if [[ "$(get_distro id)" == +(debian|ubuntu) ]]; then
@@ -523,6 +627,10 @@ while [ "$#" -gt 0 ]; do
   -i | -l | -p | --include | --list | --packages)
     include_packages="$2"
     shift 2
+    ;;
+  -u | --update)
+    check_update
+    exit $?
     ;;
   --)
     break
