Update ipcalc installation for --include-commands. Removed from --include-packages because this is a customized package.

diff --git a/maxibuild b/maxibuild
--- a/maxibuild
+++ b/maxibuild
@@ -222,77 +222,6 @@ maxibuild() {
         fi
         get_status_message "$?"
         echo ""
-      elif [[ "${required_pkg}" == +(ipcalc) ]]; then
-        local ipcalc_bin script_install_path
-        script_install_path="/usr/local/opencode/ipcalc"
-        ipcalc_bin="${script_install_path}/build/ipcalc"
-        echo "[${caller}]: Removing the old ipcalc installation ..."
-        if [[ "$(get_distro id)" == +(debian|ubuntu) ]]; then
-          apt-get -y remove ipcalc
-        elif [[ "$(get_distro id)" == +(centos|rhel|almalinux|rockylinux) ]]; then
-          yum -y remove ipcalc
-        fi
-        get_status_message "$?"
-        echo ""
-
-        echo "[${caller}]: Removing the old ipcalc directory"
-        rm -rf "${script_install_path}" /usr/local/bin/ipcalc /usr/bin/ipcalc
-        get_status_message "$?"
-        echo ""
-
-        echo "[${caller}]: Install required packages to build ipcalc ..."
-        apt-get -y install git gcc meson
-        get_status_message "$?"
-        echo ""
-
-        echo "[${caller}]: Creating an installation directory for ipcalc ..."
-        mkdir -p "${script_install_path}"
-        get_status_message "$?"
-        echo ""
-
-        echo "[${caller}]: Cloning the ipcalc repository ..."
-        git clone https://github.com/sofibox/ipcalc.git "${script_install_path}"
-        get_status_message "$?"
-        echo ""
-
-        # Change directory to script_install_path, if failed then exit with a message
-        cd "${script_install_path}" || {
-          echo "Failed to change directory to ${script_install_path}"
-          exit 1
-        }
-
-        echo "[${caller}]: Configuring ipcalc build type ..."
-        meson setup build --buildtype=release
-        get_status_message "$?"
-        echo ""
-
-        echo "[${caller}]: Building ipcalc ..."
-        ninja -C build
-        get_status_message "$?"
-        echo ""
-
-        echo "[${caller}]: Giving execution permission to the ipcalc installation script ..."
-        chmod +x ${ipcalc_bin}
-        get_status_message "$?"
-        echo ""
-
-        echo "[${caller}]: Creating a symbolic link to the ipcalc installation script ..."
-        ln -s ${ipcalc_bin} /usr/local/bin
-        get_status_message "$?"
-        echo ""
-
-        #echo "[${caller}]: Copying sample config file ..."
-        #cp "${script_install_path}/ipcalc.conf.sample" "${script_install_path}/ipcalc.conf"
-        #echo ""
-
-        # echo "[${caller}]: Running ipcalc --version  ..."
-        # ipcalc --version
-        # get_status_message "$?"
-        # retval=$?
-
-        command -v "${required_pkg}" &>/dev/null
-        get_status_message "$?"
-
       else
         apt -y install "${required_pkg}"
         get_status_message "$?"
@@ -366,75 +295,80 @@ maxibuild() {
         fi
         get_status_message "$?"
         echo ""
-      elif [ "${required_cmd}" == "ipcalc" ]; then
+      elif [[ "${required_cmd}" == +(ipcalc) ]]; then
+
+        local ipcalc_bin script_install_path
+        script_install_path="/usr/local/opencode/ipcalc"
+        ipcalc_bin="${script_install_path}/build/ipcalc"
+
+        echo "[${caller}]: Removing the old ipcalc installation ..."
         if [[ "$(get_distro id)" == +(debian|ubuntu) ]]; then
-          local ipcalc_bin script_install_path
-          script_install_path="/usr/local/opencode/ipcalc"
-          ipcalc_bin="${script_install_path}/build/ipcalc"
-
-          echo "[${caller}]: Removing the old ipcalc installation ..."
           apt-get -y remove ipcalc
-          get_status_message "$?"
-          echo ""
-
-          echo "[${caller}]: Removing the old ipcalc directory"
-          rm -rf "${script_install_path}" /usr/local/bin/ipcalc /usr/bin/ipcalc
-          get_status_message "$?"
-          echo ""
-
-          echo "[${caller}]: Install required packages to build ipcalc ..."
-          apt-get -y install git gcc meson
-          get_status_message "$?"
-          echo ""
-
-          echo "[${caller}]: Creating an installation directory for ipcalc ..."
-          mkdir -p "${script_install_path}"
-          get_status_message "$?"
-          echo ""
-
-          echo "[${caller}]: Cloning the ipcalc repository ..."
-          git clone https://github.com/sofibox/ipcalc.git "${script_install_path}"
-          get_status_message "$?"
-          echo ""
-
-          # Change directory to script_install_path, if failed then exit with a message
-          cd "${script_install_path}" || {
-            echo "Failed to change directory to ${script_install_path}"
-            exit 1
-          }
-
-          echo "[${caller}]: Configuring ipcalc build type ..."
-          meson setup build --buildtype=release
-          get_status_message "$?"
-          echo ""
-
-          echo "[${caller}]: Building ipcalc ..."
-          ninja -C build
-          get_status_message "$?"
-          echo ""
-
-          echo "[${caller}]: Giving execution permission to the ipcalc installation script ..."
-          chmod +x ${ipcalc_bin}
-          get_status_message "$?"
-          echo ""
-
-          echo "[${caller}]: Creating a symbolic link to the ipcalc installation script ..."
-          ln -s ${ipcalc_bin} /usr/local/bin
-          get_status_message "$?"
-          echo ""
-
-          #echo "[${caller}]: Copying sample config file ..."
-          #cp "${script_install_path}/ipcalc.conf.sample" "${script_install_path}/ipcalc.conf"
-          #echo ""
-
-          # echo "[${caller}]: Running ipcalc --version  ..."
-          # ipcalc --version
-          # get_status_message "$?"
-          # retval=$?
-
-          command -v "${required_cmd}" &>/dev/null
-          get_status_message "$?"
+        elif [[ "$(get_distro id)" == +(centos|almalinux|rockylinux) ]]; then
+          yum -y remove ipcalc
         fi
+
+        get_status_message "$?"
+        echo ""
+
+        echo "[${caller}]: Removing the old ipcalc directory"
+        rm -rf "${script_install_path}" /usr/local/bin/ipcalc /usr/bin/ipcalc
+        get_status_message "$?"
+        echo ""
+
+        echo "[${caller}]: Install required packages to build ipcalc ..."
+        apt-get -y install git gcc meson
+        get_status_message "$?"
+        echo ""
+
+        echo "[${caller}]: Creating an installation directory for ipcalc ..."
+        mkdir -p "${script_install_path}"
+        get_status_message "$?"
+        echo ""
+
+        echo "[${caller}]: Cloning the ipcalc repository ..."
+        git clone https://github.com/sofibox/ipcalc.git "${script_install_path}"
+        get_status_message "$?"
+        echo ""
+
+        # Change directory to script_install_path, if failed then exit with a message
+        cd "${script_install_path}" || {
+          echo "Failed to change directory to ${script_install_path}"
+          exit 1
+        }
+
+        echo "[${caller}]: Configuring ipcalc build type ..."
+        meson setup build --buildtype=release
+        get_status_message "$?"
+        echo ""
+
+        echo "[${caller}]: Building ipcalc ..."
+        ninja -C build
+        get_status_message "$?"
+        echo ""
+
+        echo "[${caller}]: Giving execution permission to the ipcalc installation script ..."
+        chmod +x ${ipcalc_bin}
+        get_status_message "$?"
+        echo ""
+
+        echo "[${caller}]: Creating a symbolic link to the ipcalc installation script ..."
+        ln -s ${ipcalc_bin} /usr/local/bin
+        get_status_message "$?"
+        echo ""
+
+        #echo "[${caller}]: Copying sample config file ..."
+        #cp "${script_install_path}/ipcalc.conf.sample" "${script_install_path}/ipcalc.conf"
+        #echo ""
+
+        # echo "[${caller}]: Running ipcalc --version  ..."
+        # ipcalc --version
+        # get_status_message "$?"
+        # retval=$?
+
+        command -v "${required_cmd}" &>/dev/null
+        get_status_message "$?"
+
       elif [ "${required_cmd}" == "maxipi" ]; then
         if [[ "$(get_distro id)" == +(debian|ubuntu|centos|almalinux) ]]; then
           local maxipi_bin script_install_path
