Added copy blcheck sample file
Added wpcli/wp installation

diff --git a/maxibuild b/maxibuild
--- a/maxibuild
+++ b/maxibuild
@@ -2,7 +2,7 @@
 #"=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~="
 # ==================================================
 _APP_SPECIFIC_NAME="Maxibuild"
-_APP_VERSION="0.2.7"
+_APP_VERSION="0.2.8"
 _APP_STATUS="alpha"
 _APP_INFO="${_APP_SPECIFIC_NAME} is a bash script to manage packages."
 _APP_VERSION_STATUS="${_APP_VERSION}-${_APP_STATUS}"
@@ -181,7 +181,7 @@ maxibuild() {
 
   for required_cp in ${required_cps[*]}; do
 
-    if [[ "${required_cp}" = +(mail|linode-cli|ipcalc|maxipi|maxiaide|maxigpg|maxiperm|maxida|dbxcli|ip|pstree|netstat|puttygen|grepaddr|gotify-server|gotify-client|blcheck) ]]; then
+    if [[ "${required_cp}" = +(mail|linode-cli|ipcalc|maxipi|maxiaide|maxigpg|maxiperm|maxida|dbxcli|ip|pstree|netstat|puttygen|grepaddr|gotify-server|gotify-client|blcheck|wp|wpcli) ]]; then
 
       local cmd_status retval
       # Using command to obtain installation status
@@ -1063,8 +1063,69 @@ maxibuild() {
             get_status_message "$?"
             echo ""
 
+            echo "[${caller}]: Copying the blcheck sample configuration file ..."
+            cp "${script_install_path}/blcheck.conf.sample" "${script_install_path}/blcheck.conf"
+            get_status_message "$?"
+            echo ""
+
             echo "[${caller}]: Checking whether blcheck command is available ..."
             command -v blcheck &>/dev/null
+            get_status_message "$?"
+
+          fi
+
+        elif [[ "${required_cp}" == +(wpcli|wp) ]]; then
+          if [[ "$(get_distro id)" == +(debian|ubuntu|centos|almalinux|rockylinux) ]]; then
+            local wpcli_bin script_install_path
+
+            script_install_path="/usr/local/opencode/wpcli"
+            wpcli_bin="${script_install_path}/wp"
+
+            echo "[${caller}]: Removing the old wpcli installation"
+            rm -rf "${script_install_path}" "/usr/local/bin/wp" "/usr/bin/wp"
+            get_status_message "$?"
+            echo ""
+
+            echo "[${caller}]: Creating an installation directory for wpcli ..."
+            mkdir -p "${script_install_path}"
+            get_status_message "$?"
+            echo ""
+
+            cd "${script_install_path}" || {
+              echo "[${caller}]: ERROR, could not change directory to ${script_install_path}"
+              exit 1
+            }
+
+            echo "[${caller}]: Downloading wpcli ..."
+            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
+            get_status_message "$?"
+            echo ""
+
+            echo "[${caller}]: Giving execute permission to wp-cli.phar ..."
+            chmod +x wp-cli.phar
+            get_status_message "$?"
+            echo ""
+
+            echo "[${caller}]: Renaming wp-cli.phar to wp ..."
+            mv wp-cli.phar wp
+            get_status_message "$?"
+            echo ""
+
+            echo "[${caller}]: Creating a symbolic link for wp ..."
+            ln -s "${wpcli_bin}" "/usr/local/bin"
+            get_status_message "$?"
+            echo ""
+
+
+            # If you don't have PHP CLI installed, you will get this error when you run the command wp
+            # /usr/bin/env: 'php': No such file or directory
+            # To fix this, install php-cli
+
+            echo "WP-CLI has been installed. Please note that you need a PHP version >= 5.6.20 to run wp-cli"
+            echo ""
+
+            echo "[${caller}]: Checking whether wp command is available ..."
+            command -v wp &>/dev/null
             get_status_message "$?"
 
 
